{{- $currentScope := .}}
{{- range $jobName, $jobData := .Values.flink_jobs }}
{{- if $jobData.enabled }}
{{- with $currentScope }}
{{ $component := "taskmanager" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" $jobName $component }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  annotations:
    checksum/config: {{ .Files.Glob "configs/*" | toYaml | sha256sum }}
    checksum/job-config: {{ $jobData | toYaml | sha256sum }}
  {{- if .Values.commonAnnotations }}
    {{ include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "common.names.name" . }}
      app.kubernetes.io/component: {{ printf "%s-%s" $jobName $component }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "common.names.name" . }}
        app.kubernetes.io/component: {{ printf "%s-%s" $jobName $component }}
      annotations:
        checksum/config: {{ .Files.Glob "configs/*" | toYaml | sha256sum }}
        checksum/job-config: {{ $jobData | toYaml | sha256sum }}
    spec:
      {{- if .Values.global.serviceAccount.create }}
      serviceAccountName: {{ .Values.global.serviceAccount.name }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: remove-faas-presto-jar
          image: busybox:1.35
          command: ["sh", "-c", "rm -f /opt/flink/lib/flink-aaa-s3-fs-presto-1.13.5.jar"]
          volumeMounts:
            - name: flink-lib-volume
              mountPath: /opt/flink/lib
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: {{ .Values.taskmanager.flink_work_dir }}
          command: ["/opt/flink/bin/taskmanager.sh"]
          args: ["start-foreground",
  {{- if eq .Values.global.checkpoint_store_type "azure" }}
            "-Dfs.azure.account.key.{{ .Values.global.object_storage_endpoint }}={{ .Values.global.cloud_storage_secret_key }}",
  {{- end }}
  {{- if eq .Values.global.checkpoint_store_type "gcs" }}
            "-Dgoogle.cloud.auth.service.account.enable=true",
            "-Dfs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem",
            "-Dfs.AbstractFileSystem.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS",
            "-DHADOOP_CONF_DIR=/opt/flink/conf",
  {{- end }}
  {{- if eq .Values.global.checkpoint_store_type "s3" }}
            "-Ds3.access-key={{ .Values.s3_access_key }}",
            "-Ds3.secret-key={{ .Values.s3_secret_key }}",
            "-Ds3.endpoint={{ .Values.s3_endpoint }}",
            "-Ds3.path.style.access={{ .Values.s3_path_style_access }}",
  {{- end }}
            "-Dweb.submit.enable=false",
            "-Dmetrics.reporter.prom.class=org.apache.flink.metrics.prometheus.PrometheusReporter",
            "-Dmetrics.reporter.prom.host={{ $jobName }}-taskmanager",
            "-Dmetrics.reporter.prom.port=9251-9260",
            "-Djobmanager.rpc.address={{ $jobName }}-jobmanager",
            "-Dtaskmanager.rpc.port={{ .Values.taskmanager.rpc_port }}"]
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
          - name: flink-config-volume
            mountPath: /opt/flink/conf/flink-conf.yaml
            subPath: flink-conf.yaml
          - name: flink-config-volume
            mountPath: /opt/flink/conf/log4j-console.properties
            subPath: log4j-console.properties
          - name: flink-lib-volume
            mountPath: /opt/flink/lib
      volumes:
      - name: flink-config-volume
        configMap:
          name: {{ $jobName }}-config
          items:
          - key: flink-conf
            path: flink-conf.yaml
          - key: log4j_console_properties
            path: log4j-console.properties
      - name: flink-lib-volume
        emptyDir: {}
{{- end }}
{{- end }}
{{- end }}

