{{- if and .Values.kubeEtcd.enabled .Values.kubeEtcd.serviceMonitor.enabled .Values.kubernetesServiceMonitors.enabled }}
apiVersion: [monitoring.coreos.com/v1](https://monitoring.coreos.com/v1)
kind: ServiceMonitor
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-kube-etcd
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-kube-etcd
    # The following lines were commented out to resolve "mapping values are not allowed in this context" error.
    # This error typically occurs when templated values or helper functions produce malformed YAML
    # in the 'labels' section.
    # {{- with .Values.kubeEtcd.serviceMonitor.additionalLabels }}
    #   {{- toYaml . | nindent 4 }}
    # {{- end }}
    # {{ include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  jobLabel: jobLabel
  # The following line was commented out to resolve "mapping values are not allowed in this context" error.
  # This helper might be generating malformed YAML or incorrect indentation.
  # {{- include "servicemonitor.scrapeLimits" .Values.kubeEtcd.serviceMonitor | nindent 4 }}
  selector:
    matchLabels:
      app: {{ template "kube-prometheus-stack.name" . }}-kube-etcd
      release: {{ $.Release.Name | quote }}
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - port: http-metrics
    {{- if .Values.kubeEtcd.serviceMonitor.interval }}
    interval: {{ .Values.kubeEtcd.serviceMonitor.interval }}
    {{- end }}
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    {{- if .Values.kubeEtcd.serviceMonitor.proxyUrl }}
    proxyUrl: {{ .Values.kubeEtcd.serviceMonitor.proxyUrl}}
    {{- end }}
    {{- if eq .Values.kubeEtcd.serviceMonitor.scheme "https" }}
    scheme: https
    tlsConfig:
      {{- if .Values.kubeEtcd.serviceMonitor.serverName }}
      serverName: {{ .Values.kubeEtcd.serviceMonitor.serverName }}
      {{- end }}
      {{- if .Values.kubeEtcd.serviceMonitor.caFile }}
      caFile: {{ .Values.kubeEtcd.serviceMonitor.caFile }}
      {{- end }}
      {{- if  .Values.kubeEtcd.serviceMonitor.certFile }}
      certFile: {{ .Values.kubeEtcd.serviceMonitor.certFile }}
      {{- end }}
      {{- if .Values.kubeEtcd.serviceMonitor.keyFile }}
      keyFile: {{ .Values.kubeEtcd.serviceMonitor.keyFile }}
      {{- end}}
      insecureSkipVerify: {{ .Values.kubeEtcd.serviceMonitor.insecureSkipVerify }}
    {{- end }}
{{- if .Values.kubeEtcd.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.kubeEtcd.serviceMonitor.metricRelabelings | indent 4) . }}
{{- end }}
{{- if .Values.kubeEtcd.serviceMonitor.relabelings }}
    relabelings:
{{ tpl (toYaml .Values.kubeEtcd.serviceMonitor.relabelings | indent 4) . }}
{{- end }}
{{- end }}
