# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "demotfstatesunbird"
    key            = "./terraform.tfstate"
    region         = "ap-south-1"
    dynamodb_table = "demo-terraform-lock"
    encrypt        = true
  }
}
