{{- $currentScope := . }}
{{- range $jobName, $jobData := .Values.secor_jobs }}
{{- if $jobData.enabled }}
{{- with $currentScope }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: {{ $jobName }}-config
  name: {{ $jobName }}
  labels:
    app: secor
    release: {{ $jobName }}
spec:
  serviceName: secor
  updateStrategy:
    type: RollingUpdate
  replicas: {{ $jobData.replicas }}
  selector:
    matchLabels:
      app: secor
      release: {{ $jobName }}
  template:
    metadata:
      labels:
        app: secor
        release: {{ $jobName }}
    spec:
      {{- if and .Values.serviceAccount .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: change-pv-dir-ownership
          image: alpine:3
          command: ["/bin/sh", "-c"]
          args: ["chown -R 9999:9999 /mnt/data"]
          volumeMounts:
            - name: data-path
              mountPath: /mnt/data
      containers:
        - name: {{ $jobName }}-secor
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CONFIG_FILE
              value: "/opt/secor/config/secor.partition.properties"
            - name: LOG4J_CONFIGURATION
              value: "/opt/secor/config/log4j.docker.properties"
          volumeMounts:
            - mountPath: /opt/secor/config
              name: secor-config
            - name: data-path
              mountPath: /mnt/data
          resources:
            requests:
              cpu: {{ get $jobData.requests "cpu" }}
              memory: {{ get $jobData.requests "memory" }}
          securityContext:
            runAsUser: 9999
      volumes:
        - name: secor-config
          configMap:
            name: {{ $jobName }}-config

  volumeClaimTemplates:
    - metadata:
        name: data-path
        labels:
          app: secor
      spec:
        storageClassName: {{ $jobData.storage.storageClass | default $.Values.global.storage_class | quote }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ get $jobData.storage "size" }}
{{- end }}
{{- end }}
{{- end }}

