{{- $currentScope := . }}
{{- range $jobName, $jobData := .Values.flink_jobs }}
{{- if and (kindIs "map" $jobData) (hasKey $jobData "enabled") (index $jobData "enabled") }}
{{- with $currentScope }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" $jobName }}
  labels:
    {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  flink-conf: |-
    {{- include "common.tplvalues.render" (dict "value" (index $jobData "flink-conf") "context" $) | nindent 4 }}

  config: |-
    {{- tpl $jobData.config $ | nindent 4 }}

  base-config: |-
    {{- tpl .Values.base_config $ | nindent 4 }}

  log4j_console_properties: |-
    {{- tpl .Values.log4j_console_properties $ | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
