apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.spark.persistence.spark_data_pvc.size }}
  storageClassName: {{ .Values.global.storage_class }}


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.spark.persistence.log_data_pvc.size }}
  storageClassName: {{ .Values.global.storage_class }}