{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
{{ include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
{{ include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
{{- $currentScope := . }}
{{- range $path, $_ := .Files.Glob "configs/*" }} # Take only root level files (configs/*) for configmaps
  {{- if ne $path "configs/env.yaml" }} # Skip env.yaml as configmap, as it's env file
  {{ base $path | nindent 2 }}: |-
    {{- with $currentScope }}
    {{- $var := .Files.Get $path }}
    {{- /* SAFELY render tpl to prevent nil pointer errors */}}
    {{- tpl $var (dict "Values" (default dict .Values) "Release" .Release "Chart" .Chart "Files" .Files "Capabilities" .Capabilities "Template" .Template "Context" .) | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}

